### ISSUE TITLE
各自が開発用のGitHubリポジトリのgit cloneやgit pushができるか確認する

### ISSUE THREAD

**Issue by sasayakitei** [kojikadowaki/freemarket_sample_67b#1]
題名の通りです。
完了したらこのissueに完了報告をお願いします。
実装作業はみなさんの確認が終わるまでお待ちを！

**Comment by sasayakitei** [comment]
南條です
git cloneとgit pushともに問題なくできました。

**Comment by kojikadowaki** [comment]
門脇です。
git push完了しました。

**Comment by kaito0402** [comment]
岡安です。
git push 完了しました！

**Comment by CrazyForTimtam** [comment]
坂本です。
git push 完了しました！

**Comment by sasayakitei** [comment]
みなさん問題なくリモートpushできたのでこのissueはクローズします
