### ISSUE TITLE
# 商品出品時のエラーハンドリングについて

### ISSUE THREAD

**Issue by kaito0402** [kojikadowaki/freemarket_sample_67b#20]
お疲れ様です！
表題の件で詰まってしまってます。皆さんのお知恵をお借りできればと思います。

# 実現させたい挙動
商品出品時、必須項目を入力せずに出品すると出品画面に戻り、「〜件のエラーが発生しました。+具体的なエラー文」というような表示をさせたい。

# 現状の挙動
以下のエラー文が表示される。（当たり前ですが、出品に必要な情報が入ってませんよというエラーです。）
https://gyazo.com/92cf9a282372a59b2a7b43343d9e361d

以下、この実装に関わるコードです。
・商品出品画面です。3行目から8行目にエラー件数、エラー内容が表示される記述をしています。
https://gyazo.com/f391bc49bf4671fa7b74dafe58d53042

・productコントローラー、createアクションの記述です。出品の際、送られたデータが保存されればトップページに、されなければ、renderを使い商品出品画面に戻る処理をしています。
https://gyazo.com/df4dac00573cf730dcb59cc1a7d8de7f

この件について、お気づきのことがあれば何でも共有いただけますと幸いです。
皆さんお忙しいと思いますが、よろしくお願い致します。

岡安

**Comment by sasayakitei** [comment]
お疲れさまです。南條です。

#createアクションで以下のインスタンス変数が定義されていないのが原因な気がします。
"@category_parents"

違っていたらごめんなさい。

**Comment by kaito0402** [comment]
南條さん、早速のご返信ありがとうございます！
南條さんのご指摘…ビンゴ！でした！

無事に商品購入画面に戻り、エラーも表示されました！
本当にありがとうございました！

こちら、問題が解決したのでissueをクローズさせていただきます！
