### ISSUE TITLE
ER図の確認

### ISSUE THREAD

**Issue by CrazyForTimtam** [kojikadowaki/freemarket_sample_67b#3]
DB設計上のER図を作成しましたので、ご確認をお願い致します！
皆さんからOKをいただいた後、readmeへの記載に進みます

何か疑問やご指摘あれば、なんでも仰ってくださいm(_ _)m

https://gyazo.com/57cf3b71beeba7e5e68eb573d13e31d7

**Comment by CrazyForTimtam** [comment]
【ER図修正ver.】
１番大事な"usersテーブル"と"productsテーブル"間のリレーションが抜けてしまっていたので、修正しましたm(_ _)m
ER図内、赤で記しているものが追記リレーションです。

https://gyazo.com/046ebd0fe168927e993c273e930f3938

**Comment by sasayakitei** [comment]
お疲れさまです。南條です。
ER図確認させていただきました。
パッと見の意見ですが基本的にこれをベースにしていけばよいと思います。
私の目から見て改善できそうな点が2点ありましたのでご報告します。

* productsテーブルのproduct-image_idカラムは不要かと思います。
  product-imagesテーブルにproduct_idカラムがあればOK
* テーブルやカラムの単語区切りは"-"よりも"_"がよいかと思います。
  Railsのテーブル名の規則としてスネークケースの複数系というルールがあるため
  例）product-images → product_images

何かありましたらご指摘・補足いただければ有り難いです。

**Comment by CrazyForTimtam** [comment]
@sasayakitei 
南條さん、ご指摘ありがとうございます！
修正致しました！

**Comment by CrazyForTimtam** [comment]
# ER図修正後の再確認依頼
本日4/1(水)のデイリーミーティングで皆さんにご指摘いただいた箇所を修正しました🙌
お手数ですが、改めてご確認をお願い致します。

# 【修正点】
・productsテーブル内、product-image_idの削除
・テーブル名やカラム名をスネークケースを用いた名前に修正
・ordersテーブルの追加
・category_sizesテーブルの追加

https://gyazo.com/0bf2285177377c5950258ade68a2da95

**Comment by kaito0402** [comment]
岡安です。
ER図確認しました！
自分はこれで問題ないと思います！

**Comment by shota-code** [comment]
ER図を元にReadmeを作成しました。
ご確認をよろしくお願いします。

# README
# DB設計
## usersテーブル
|Column|Type|Options|
|------|----|-------|
|nickname|string|null: false|
|email|string|null: false, unique: true, index: true|
|password|integer|null: false|
### Association
- has_many :products
- has_many :comments
- has_many :orders
- belongs_to :profile
- belongs_to :credit_card
- belongs_to :shipping_address

## profilesテーブル
|Column|Type|Options|
|------|----|-------|
|first_name|string|null: false|
|family_name|string|null: false|
|first_name_kana|string|null: false|
|family_name_kana|string|null: false|
|birth_year|integer|null: false|
|birth_month|integer|null: false|
|birth_day|integer|null: false|
|avatar|string|null: false|
|user_id|references|null: false, foreign_key: true|
### Association
- belongs_to :user

## credit_cardsテーブル
|Column|Type|Options|
|------|----|-------|
|card_number|integer|null: false, unique: true, index: true|
|expiration_year|integer|null: false|
|expiration_month|integer|null: false|
|security_code|integer|null: false|
|user_id|references|null: false, foreign_key: true|
### Association
- belongs_to :user

### shipping-addressesテーブル
|Column|Type|Options|
|------|----|-------|
|address_first_name|string|null: false|
|address_family_name|string|null: false|
|address_first_name_kana|string|null: false|
|address_family_name_kana|string|null: false|
|post_code|integer|null: false|
|prefecture|string|null: false|
|city|string|null: false|
|address_number|integer|null: false|
|building_name|string|null: false|
|phone_number|integer|null: false|
|user_id|references|null: false, foreign_key: true|
#### Association
- belongs_to :user

## productsテーブル
|Column|Type|Options|
|------|----|-------|
|name|string|null: false|
|price|integer|null: false|
|description|text|null: false|
|size_id|references|null: false, foreign_key: true|
|ship_from_location_id|references|null: false, foreign_key: true|
|product_condition_id|references|null: false, foreign_key: true|
|derivery_fee_payer_id|references|null: false, foreign_key: true|
|derivery_day_id|references|null: false, foreign_key: true|
|category_id|references|null: false, foreign_key: true|
|user_id|references|null: false, foreign_key: true|
### Association
- has_many :products
- has_many :comments
- has_many :product_images
- belongs_to :size
- belongs_to :ship_from_location
- belongs_to :product_condition
- belongs_to :derivery_fee_payer
- belongs_to :derivery_day
- belongs_to :category
- belongs_to :order

## product_imagesテーブル
|Column|Type|Options|
|------|----|-------|
|url|string|null: false|
|product_id|references|null: false, foreign_key: true|
### Association
- belongs_to :product

## sizesテーブル
|Column|Type|Options|
|------|----|-------|
|size|string|null: false|
###Association
- has_many :products
- has_many :sizes, through: :category_sizes

## ship_from_locationsテーブル
|Column|Type|Options|
|------|----|-------|
|ship_from_location|string|null: false|
### Association
- has_many :products

## product_conditionsテーブル
|Column|Type|Options|
|------|----|-------|
|product_condition|string|null: false|
### Association
- has_many :products

## derivery_fee_payersテーブル
|Column|Type|Options|
|------|----|-------|
|derivery_fee_payer|string|null: false|
### Association
- has_many :products

## derivery_daysテーブル
|Column|Type|Options|
|------|----|-------|
|derivery_day|integer|null: false|
### Association
- has_many :products

## categoriesテーブル
|Column|Type|Options|
|------|----|-------|
|name|string|null: false|
|ancestry|string|null: false|
### Association
- has_many :products
- has_many :sizes, through: :category_sizes

## category_sizesテーブル
|Column|Type|Options|
|------|----|-------|
|category_id|references|null: false, foreign_key: true|
|size_id|references|null: false, foreign_key: true|
### Association
- belongs_to :category
- belongs_to :size

## commentsテーブル
|Column|Type|Options|
|------|----|-------|
|text|text|null: false|
|user_id|references|null: false, foreign_key: true|
|product_id|references|null: false, foreign_key: true|
### Association
- belongs_to :user
- belongs_to :product

## ordersテーブル
|Column|Type|Options|
|------|----|-------|
|buyer_user_id|references|null: false, foreign_key: true|
|product_id|references|null: false, foreign_key: true|
### Association
- belongs_to: user
- belongs_to: product

**Comment by shota-code** [comment]
sizesテーブルの表記がおかしくなっていたので、修正しました。
こちらの方でご確認をお願いします。

# README
# DB設計
## usersテーブル
|Column|Type|Options|
|------|----|-------|
|nickname|string|null: false|
|email|string|null: false, unique: true, index: true|
|password|integer|null: false|
### Association
- has_many :products
- has_many :comments
- has_many :orders
- belongs_to :profile
- belongs_to :credit_card
- belongs_to :shipping_address

## profilesテーブル
|Column|Type|Options|
|------|----|-------|
|first_name|string|null: false|
|family_name|string|null: false|
|first_name_kana|string|null: false|
|family_name_kana|string|null: false|
|birth_year|integer|null: false|
|birth_month|integer|null: false|
|birth_day|integer|null: false|
|avatar|string|null: false|
|user_id|references|null: false, foreign_key: true|
### Association
- belongs_to :user

## credit_cardsテーブル
|Column|Type|Options|
|------|----|-------|
|card_number|integer|null: false, unique: true, index: true|
|expiration_year|integer|null: false|
|expiration_month|integer|null: false|
|security_code|integer|null: false|
|user_id|references|null: false, foreign_key: true|
### Association
- belongs_to :user

### shipping-addressesテーブル
|Column|Type|Options|
|------|----|-------|
|address_first_name|string|null: false|
|address_family_name|string|null: false|
|address_first_name_kana|string|null: false|
|address_family_name_kana|string|null: false|
|post_code|integer|null: false|
|prefecture|string|null: false|
|city|string|null: false|
|address_number|integer|null: false|
|building_name|string|null: false|
|phone_number|integer|null: false|
|user_id|references|null: false, foreign_key: true|
#### Association
- belongs_to :user

## productsテーブル
|Column|Type|Options|
|------|----|-------|
|name|string|null: false|
|price|integer|null: false|
|description|text|null: false|
|size_id|references|null: false, foreign_key: true|
|ship_from_location_id|references|null: false, foreign_key: true|
|product_condition_id|references|null: false, foreign_key: true|
|derivery_fee_payer_id|references|null: false, foreign_key: true|
|derivery_day_id|references|null: false, foreign_key: true|
|category_id|references|null: false, foreign_key: true|
|user_id|references|null: false, foreign_key: true|
### Association
- has_many :products
- has_many :comments
- has_many :product_images
- belongs_to :size
- belongs_to :ship_from_location
- belongs_to :product_condition
- belongs_to :derivery_fee_payer
- belongs_to :derivery_day
- belongs_to :category
- belongs_to :order

## product_imagesテーブル
|Column|Type|Options|
|------|----|-------|
|url|string|null: false|
|product_id|references|null: false, foreign_key: true|
### Association
- belongs_to :product

## sizesテーブル
|Column|Type|Options|
|------|----|-------|
|size|string|null: false|
### Association
- has_many :products
- has_many :sizes, through: :category_sizes

## ship_from_locationsテーブル
|Column|Type|Options|
|------|----|-------|
|ship_from_location|string|null: false|
### Association
- has_many :products

## product_conditionsテーブル
|Column|Type|Options|
|------|----|-------|
|product_condition|string|null: false|
### Association
- has_many :products

## derivery_fee_payersテーブル
|Column|Type|Options|
|------|----|-------|
|derivery_fee_payer|string|null: false|
### Association
- has_many :products

## derivery_daysテーブル
|Column|Type|Options|
|------|----|-------|
|derivery_day|integer|null: false|
### Association
- has_many :products

## categoriesテーブル
|Column|Type|Options|
|------|----|-------|
|name|string|null: false|
|ancestry|string|null: false|
### Association
- has_many :products
- has_many :sizes, through: :category_sizes

## category_sizesテーブル
|Column|Type|Options|
|------|----|-------|
|category_id|references|null: false, foreign_key: true|
|size_id|references|null: false, foreign_key: true|
### Association
- belongs_to :category
- belongs_to :size

## commentsテーブル
|Column|Type|Options|
|------|----|-------|
|text|text|null: false|
|user_id|references|null: false, foreign_key: true|
|product_id|references|null: false, foreign_key: true|
### Association
- belongs_to :user
- belongs_to :product

## ordersテーブル
|Column|Type|Options|
|------|----|-------|
|buyer_user_id|references|null: false, foreign_key: true|
|product_id|references|null: false, foreign_key: true|
### Association
- belongs_to: user
- belongs_to: product

**Comment by CrazyForTimtam** [comment]
@kaito0402 
確認ありがとうございます！

**Comment by sasayakitei** [comment]
お疲れさまです、南條です。
テーブル設計確認ありがとうございます！
デイリースクラムでも確認しましたが、私が気になったのは以下2点です。

①profilesテーブルのavatarカラムはnot null制約不要
②shipping_addressesテーブルのaddress_numberカラムはnot null制約不要

**Comment by sasayakitei** [comment]
@shota-code 
度々すみません。ユーザ登録部分を実装中に、新たに疑問箇所を発見してしまいました。

## usersテーブルのAssociation
* belongs_to :profile
* belongs_to :credit_card
* belongs_to :shipping_address

こちらですが、以下のAssociationのほうがよいかと思います。
* has_one :profile
* has_one :credit_card
* has_one :shipping_address

has_oneはhas_manyの1対1バージョンみたいな感じです。

＜参考記事＞
https://qiita.com/color_box/items/2147461a64d6b9e583c9

**Comment by shota-code** [comment]
@sasayakitei 
ご指摘ありがとうございます。
坂本さんからも同じご指摘をいただいたので、そこを明日までに直したいと思います。

**Comment by CrazyForTimtam** [comment]
お疲れ様です！坂本です。
テーブル設計作業、ありがとうございます！
また、南條さんご確認ありがとうございます！
いくつか気になる点がありましたので、ご確認お願い致します。

# shipping_addressesテーブルのphone_numberカラム
昨日のミーティングで、南條さんに任意項目なのでnot null制約不要とご指摘いただきましたが、
これに加えて「unique: true」を追記した方がいいのかな？？と思いました。
電話番号は任意項目ですが、ユーザーがもし入力した場合、入力間違えの可能性も考え（１桁間違えただけで違う人に繋がってしまったり...ということもあるので）既存のデータと重複していないか確認されるようにした方がいいのかなと思ったのですが、皆さんのご意見もいただけたら幸いですm(_ _)m

# productsテーブルのアソシエーション
「has_many :products」となっていたので、こちらを「belongs_to :user」に変更お願い致します！

# categoriesテーブルのアソシエーション
おそらく「has many :category_sizes」を追加した方が良いかと思います！

# sizesテーブルのアソシエーション
同じく「has many :category_sizes」の追加
また、「has_many :sizes, through: :category_sizes」の部分を「has_many :categories, through: :category_sizes」にご変更お願い致します！


細かな作業で大変かと思いますが、よろしくお願い致しますm(_ _)m

**Comment by shota-code** [comment]
お疲れ様です。柏木です。
ご指摘ありがとうございます。ご指摘いただいた点を直したので、ご確認をお願いいたします。



# README
# DB設計
## usersテーブル
|Column|Type|Options|
|------|----|-------|
|nickname|string|null: false|
|email|string|null: false, unique: true, index: true|
|password|integer|null: false|
### Association
- has_many :products
- has_many :comments
- has_many :orders
- has_one :profile
- has_one :credit_card
- has_one :shipping_address

## profilesテーブル
|Column|Type|Options|
|------|----|-------|
|first_name|string|null: false|
|family_name|string|null: false|
|first_name_kana|string|null: false|
|family_name_kana|string|null: false|
|birth_year|integer|null: false|
|birth_month|integer|null: false|
|birth_day|integer|null: false|
|avatar|string|
|user_id|references|null: false, foreign_key: true|
### Association
- belongs_to :user

## credit_cardsテーブル
|Column|Type|Options|
|------|----|-------|
|card_number|integer|null: false, unique: true, index: true|
|expiration_year|integer|null: false|
|expiration_month|integer|null: false|
|security_code|integer|null: false|
|user_id|references|null: false, foreign_key: true|
### Association
- belongs_to :user

### shipping-addressesテーブル
|Column|Type|Options|
|------|----|-------|
|address_first_name|string|null: false|
|address_family_name|string|null: false|
|address_first_name_kana|string|null: false|
|address_family_name_kana|string|null: false|
|post_code|integer|null: false|
|prefecture|string|null: false|
|city|string|null: false|
|address_number|integer|null: false|
|building_name|string|
|phone_number|integer|unique: true|
|user_id|references|null: false, foreign_key: true|
#### Association
- belongs_to :user

## productsテーブル
|Column|Type|Options|
|------|----|-------|
|name|string|null: false|
|price|integer|null: false|
|description|text|null: false|
|size_id|references|null: false, foreign_key: true|
|ship_from_location_id|references|null: false, foreign_key: true|
|product_condition_id|references|null: false, foreign_key: true|
|derivery_fee_payer_id|references|null: false, foreign_key: true|
|derivery_day_id|references|null: false, foreign_key: true|
|category_id|references|null: false, foreign_key: true|
|user_id|references|null: false, foreign_key: true|
### Association
- has_many :comments
- has_many :product_images
- belongs_to :user
- belongs_to :size
- belongs_to :ship_from_location
- belongs_to :product_condition
- belongs_to :derivery_fee_payer
- belongs_to :derivery_day
- belongs_to :category
- has_one :order

## product_imagesテーブル
|Column|Type|Options|
|------|----|-------|
|url|string|null: false|
|product_id|references|null: false, foreign_key: true|
### Association
- belongs_to :product

## sizesテーブル
|Column|Type|Options|
|------|----|-------|
|size|string|null: false|
### Association
- has_many :products
- has_many :categories, through: :category_sizes
- has_many :category_sizes

## ship_from_locationsテーブル
|Column|Type|Options|
|------|----|-------|
|ship_from_location|string|null: false|
### Association
- has_many :products

## product_conditionsテーブル
|Column|Type|Options|
|------|----|-------|
|product_condition|string|null: false|
### Association
- has_many :products

## derivery_fee_payersテーブル
|Column|Type|Options|
|------|----|-------|
|derivery_fee_payer|string|null: false|
### Association
- has_many :products

## derivery_daysテーブル
|Column|Type|Options|
|------|----|-------|
|derivery_day|integer|null: false|
### Association
- has_many :products

## categoriesテーブル
|Column|Type|Options|
|------|----|-------|
|name|string|null: false|
|ancestry|string|null: false|
### Association
- has_many :products
- has_many :sizes, through: :category_sizes
- has_many :category_sizes

## category_sizesテーブル
|Column|Type|Options|
|------|----|-------|
|category_id|references|null: false, foreign_key: true|
|size_id|references|null: false, foreign_key: true|
### Association
- belongs_to :category
- belongs_to :size

## commentsテーブル
|Column|Type|Options|
|------|----|-------|
|text|text|null: false|
|user_id|references|null: false, foreign_key: true|
|product_id|references|null: false, foreign_key: true|
### Association
- belongs_to :user
- belongs_to :product

## ordersテーブル
|Column|Type|Options|
|------|----|-------|
|buyer_user_id|references|null: false, foreign_key: true|
|product_id|references|null: false, foreign_key: true|
### Association
- belongs_to: user
- belongs_to: product

**Comment by sasayakitei** [comment]
@shota-code 
お疲れさまです。南條です。
再度の修正ありがとうございます。

users, profiles, shipping_addresses, credit_cardsをメインに確認させていただきました。
たびたび申し訳ないのですが、1点追加になります。
shipping_addressesテーブルのaddress_numberカラムは住所の「番地」にあたるものになるかと思いますが、こちら、「１−５」や「１番地５号」のように記述されるものなのでintegerではなくstringが相応かと思います。
ご確認のほど宜しくお願いします。

**Comment by shota-code** [comment]
@sasayakitei 
ご指摘ありがとうございます。
修正しておきました。

**Comment by CrazyForTimtam** [comment]
柏木さんをはじめ皆さんのご協力のおかげで、DB設計無事LGTMいただきました！
ありがとうございました。
