### ISSUE TITLE
# 自動デプロイ時のエラーについて

### ISSUE THREAD

**Issue by kaito0402** [kojikadowaki/freemarket_sample_67b#33]
- 現状

自動デプロイ中以下のエラーが起こる。
https://gyazo.com/3573745181a952867df380dad732fae4

エラー文を読むと、PAYJP_PRIVATE_KEYが見つからないというエラーだと思うのですが、記載すべき場所全てにPAYJP_PRIVATE_KEYを入れているので、エラーの原因が分からない状況です。
以下、環境変数"PAYJP_PRIVATE_KEY"に関するファイルの記述です。

https://gyazo.com/4672122e8c6c1aae8d8c306efb802de5
secret.yml内の記述

https://gyazo.com/c7f0d88032f1760a2f5e425a318d2da8
EC2インスタンス内、/etc/enviromentの記述

https://gyazo.com/8b218a7c090c5fdd56dee80c484f8ed3
EC2インスタンス内、/.bash_profileの記述

以上です。
些細なことでも大丈夫ですので、お気づきの点がございましたら共有していただけるとありがたいです！

よろしくお願い致します！

**Comment by CrazyForTimtam** [comment]
@kaito0402 
お疲れ様です！坂本です
色々と調べていただきありがとうございます！

本日メンターさんに確認をしたところ、
# ①昨日個人zoomでお話した、「card_controller」内の”Payjp.api_key”の記述について
→昨日はsecrets.ymlの中の記述に合わせて、「card_controller」内の”Payjp.api_key”と記述している部分（全３箇所）を"payjp_private_key"に修正することでエラーが解消する可能性が高いというお話をしておりましたが、
こちらの記述は、修正の必要はなく、"Payjp.api_key"のままで良いそうです。

理由として、
secrets.ymlではなく、ローカルにおいてもrails5.2以下の環境であれば.bash_profile内にpayjp環境変数を置く必要があり、よって、secrets.ymlの記述は不要となる。とのことでした。

ではなぜsecrets.ymlの記述が無関係にも関わらず
私のローカル環境でクレジットカード登録機能が問題なく動いていたのかというと...
今回の実装中、色々と試行錯誤している中で、ローカル環境で.bash_profile内にも以前既に環境変数を定義していた為でしたm(_ _)m

昨日岡安さんと個人zoomさせていただいた時に、
card_controller内の”Payjp.api_key”を"payjp_private_key"に変更すると、カード削除機能などが問題なく動作しているように見えたのは、単にpayjp公式HP側のデータ処理速度がたまたま遅れていてそのように見えただけで、元々の”Payjp.api_key”の記述でそもそも問題なく動作していたはず、とのことでした。かえって内容を複雑にしてしまい、大変申し訳ございませんm(_ _)m

なので、
環境変数は、.bash_profile内の設定に問題がないか再度見直し、
secrets.yml内のdevelopmentとproduction以下の"payjp_private_key"及び"payjp_key"の記述は削除致しました。


# ②デプロイ時に起こる、PAYJP_PRIVATE_KEYが見つからないというエラーについて
こちらもメンターさんに確認をしたところ、岡安さんにご設定いただいたsecrets.yml内の記述に、ちょっとしたタイプミスがあったようです。
私もメンターさんも最後の最後まで気づけないくらい本当に小さなものだったのですが...

secrets.yml内、development及びproduction以下の
payjp_private_key: <%= ENV["PAYJP_PRIVATE_KEY"] %>
payjp_key: <%= ENV["PAYJP_KEY"] %>
こちらの記述内容の中の、ENV内ダブルクォーテーションがおそらく半角ではなく全角になっていて、アプリの方でうまく読み込まれていなかったようです💦

こちらにメンターさんが気づいた経緯なのですが、
自動デプロイ中の以下のエラーを見ていただいた時に、
![デプロイ中のエラー](https://user-images.githubusercontent.com/61226318/80462196-50e95480-8971-11ea-916c-4d5d36e44eb7.jpg)
なぜPAYJP_PRIVATE_KEYがシングルクォーテーションとダブルクォーテーションで２回も囲まれているのかというお話になり、当issueにも添付いただいているsecrets.ymlを見に行ったところ、
<img width="1050" alt="secrets ymlの内容" src="https://user-images.githubusercontent.com/61226318/80462668-00bec200-8972-11ea-8c9e-5c6be2adb81d.png">
白丸部分のダブルクォーテーションを他のawsなどのものとよく見比べてみると、何やらクォーテーションの角度が違う...？？と、奇跡的に発見に至り私もメンターさんも揃って歓声をあげました笑

よって、
secrets.yml内のダブルクォーテーションを半角に修正していただくか、
ローカルと同様、/etc/enviromentや .bash_profileに環境設定をしているのであれば、secrets.yml内のpayjpに関する記述自体を削除してしまえば、デプロイ時のエラーは解消されるはずとのことでした☺️
※また、/etc/enviromentと .bash_profileだと、前者の/etc/enviromentが先に読み込まれる為、
/etc/enviroment内にpayjpの環境変数を設定しているのであれば、.bash_profile内のpayjp環境変数は消してしまっても問題ないとのことでした！


長くなりましたが、以上が先ほどメンターさんに導いていただいた回答になります！
おそらくこちらで解決するはずですが、万が一エラーが解消されなかった場合は教えてくださいm(_ _)m

また、

何度も修正をしていただくことになり、大変申し訳ございません。
お手数ですが、お手すきの先に内容をご確認いただき修正をお願い致しますm(_ _)m
