### ISSUE TITLE
クレジットカード登録時のエラーについて

### ISSUE THREAD

**Issue by SayakaS2** [kojikadowaki/freemarket_sample_67b#46]
お疲れ様です、坂本です。
カード登録時のエラーについて共有させていただきます。
<img width="1123" alt="クレジットカード登録時のエラー" src="https://user-images.githubusercontent.com/61226318/81682839-2f6b8b00-9490-11ea-88e3-15b76c47c871.png">

カード登録時、payjp上でDBを作成する為に
「email: current_user.email」としてログインuserのemailを渡しているのですが、
<img width="964" alt="card_controller" src="https://user-images.githubusercontent.com/61226318/81682966-6772ce00-9490-11ea-94e1-35cc62010f95.png">

この時に渡されるemailが「◯@◯.◯ (例. test@test.com や a@a.a など)」の形でないと
payjp側からエラーが出されてしまうようです。
（payjp側からのエラーの為、このエラーが出ないようにすることは不可）

スプリントレビュー時に仮のユーザーを登録した際、
「k@o」のような形のemailを登録していたので、
payjp側から不正な値としてエラーが出てしまったようですm(_ _)m

なので、解決策としてuserのemailに対して、payjpエラー回避の為、
以下userモデルの31、32行目にバリデーションを追加したいと考えているのですが、
いかがでしょうかm(_ _)m
<img width="950" alt="userモデル" src="https://user-images.githubusercontent.com/61226318/81683735-570f2300-9491-11ea-999f-5d5c8835410f.png">

追記内容・追記場所等こっちの方がいいんじゃないかなどご意見ございましたら、ご指示いただけますと幸いですm(_ _)m

お手数ですがご確認をお願い致します！

**Comment by sasayakitei** [comment]
@SayakaS2 
お疲れさまです。南條です。
userのemailのバリデーションについては、モデルファイルではなく以下のdevise用の設定ファイルに記述されているようです。

ファイル名: config/initializers/devise.rb

175行目に以下の記述があり、これを書き換えてサーバを再起動するだけでバリデーションが通るものと思います。

`config.email_regexp = /\A[^@\s]+@[^@\s]+\z/`

参考記事についてもご確認ください。宜しくお願いいたします！

■参考記事
https://nekomaho.hatenablog.jp/entry/2017/03/15/005613

**Comment by SayakaS2** [comment]
@sasayakitei 
お疲れ様です！
ご回答ありがとうございます。

南條さんのおっしゃる通り、devise.rb内175行目の記述を書き換えサーバーを再起動したところ、バリデーションが通り、a@a.aの形でない場合は「メールアドレス は不正な値です」とエラーメッセージが表示され登録ができないようになりました！

#### 変更前
`config.email_regexp = /\A[^@\s]+@[^@\s]+\z/`
#### 変更後
`config.email_regexp = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i`

ありがとうございます！
