### ISSUE TITLE
ShippingAddressモデルのバリデーションに関する課題

### ISSUE THREAD

**Issue by sasayakitei** [kojikadowaki/freemarket_sample_67b#7]
お疲れ様です。南條です。
実装していて気がついた部分を共有します。ご意見いただければ有り難いです。

# post_codeカラム
## 課題
NNN-NNNNのような"-"(ハイフン)が入る入力には対応できない

## 原因
型がIntegerのため

## 解決案
1. NNNNNNNのような7桁の数字のみの入力を許容する
2. 型をStringに変更し正規表現でNNN-NNNNとNNNNNNNの2種類の入力を許容する
3. 前半の3桁と後半の4桁にカラムを分離し"-"の入力を行わせない

# phone_numberカラム
## 課題
電話番号の入力には下記のようにいくつかのパターンがあるため、すべてのパターンを許容してしまうと一意性制約が機能しない。
例）09012345678で登録されているデータがあっても090-1234-5678が登録できてしまう

### 電話番号パターン例
- 090NNNNNNNN, 03NNNNNNNN(数字のみ11桁または10桁)
- 090-NNNN-NNNN, 03-NNNN-NNNN(局番の区切りにハイフンが入る)
- 090(NNNN)NNNN, 03(NNNN)NNNN(市外局番をカッコで括る)

## 原因
制約の仕様上の問題

## 解決案
1. 入力を090NNNNNNNNのような数字のみに限定する
2. カスタムバリデーションを導入して上記のような細かいパターン分けに対応する

## メモ
2はかなりカロリーの高い実装になってしまうので、一旦1でいかせていただければ…

**Comment by kaito0402** [comment]
南條さんお疲れ様です！

課題拝見しました！
自分も１の解決案で良いと思います。実際のウェブサービスでも郵便番号や電話番号の形式を指定して入力させるパターンが多いのですし、予め指定すればユーザーの利便性にさほど影響はでないと思います。

**Comment by sasayakitei** [comment]
@kaito0402 
迅速なレスポンスありがとうございます！
ひとまずどちらも1案でバリデーションを組んでみます！

**Comment by CrazyForTimtam** [comment]
お疲れ様です。
レスポンスが遅くなり申し訳ございません。

私も同じく、事前に入力形式が指定される場合が多いと思うので、１の解決案に賛成です！
よろしくお願い致します！

**Comment by sasayakitei** [comment]
ありがとうございました。解決案については1でひとまずやっていきます。
